### ISSUE TITLE
Link/Create postmortems

### ISSUE THREAD

**Issue by TomTucka** [ministryofjustice/opg-incident-response#35]
I was thinking about this today, link to the postmortem that relates to the incident document that is created

or we could have a slack command that can be run in the channel after an incident is closed that allows you to fill out a dialogue box with our postmortem questions.

or we could have a tab on the incident page that allows the team to fill out a postmortem on the web page

@gregtyler / @acsauk any thoughts?

**Comment by gregtyler** [comment]
I think just a link is fine: postmortems are typically written on Confluence and we're never going to provide a better editing experience than them.

One reason I can think of for doing it inside the app is to collect quantifiable information so we can consistently compare data across incidents, but I don't think that's something we need.
